### PR TITLE
add licenses

### PR DESCRIPTION
**Pull request by sxren**

### CODE REVIEW

**Comment by rgrp** [comment]
@sxren did you close intentionally?

**Comment by sxren** [comment]
@rgrp is that not the right thing to do? i'm not done. but this approach is wrong.

**Comment by rgrp** [comment]
@sxren did you want this change to get merged? if you want it merged you do not want to close it as that prevents me from merging it for you. I can re-open if that is what you want. If you did not want to submit this pull request then we closing was right thing to do :-)

**Comment by sxren** [comment]
@rgrp ok. cool. :) i don't want to submit this pull request. i'll make a new one later.

**Comment by rgrp** [comment]
@sxren ok - have to say the PR looked pretty good :-)

**Comment by rgrp** [comment]
@sxren any update here? Lots of people flagged this at Open Data Maker and I'd love us to start improving the creator form. I'm also on #okfn on freenode if you need to chat.

**Pull request closed without merging**
